### ISSUE TITLE
Firebase API keys are public

### ISSUE THREAD

**Issue by Rishabhraghwendra18** [CodeFlow201/codeflow#50]
Firebase API keys are publicly exposed in code base (in firebase.js file) . Put it in environment variable .

**Comment by Rishabhraghwendra18** [comment]
I am working on it

**Comment by mostlypanda** [comment]
Hii @Rishabhraghwendra18 , the reason why all these key stuff has not been set down as environment variables because of the reason many folks are working on this piece of code so if we convert them into env variables then this project won't run locally in any of their system as they have to provide these credentials for functioning of the app. 
Yes I know this is not the right practice but we will find the better solution soon. I hope now this is clear to you.
Happy Coding!!

**Comment by Rishabhraghwendra18** [comment]
@mostlypanda you may add it in README file that contributor have to use it's own firebase API because I have seen many cases where APIs were exposed and some bad intention people used it and that cost thousands of rupees to developer .

**Comment by mostlypanda** [comment]
@Rishabhraghwendra18  Ya sure, we will do this!

**Comment by Rishabhraghwendra18** [comment]
@mostlypanda 👍
